name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          cd home-project/ststic-app
          docker build -t static-app .
    
      - name: Debug ECR_REPO_URL
        run: echo "ECR_REPO_URL=${{ secrets.ECR_REPO_URL }}"


      - name: Tag image
        run:
          docker tag static-app:latest ${{ secrets.ECR_REPO_URL }}:latest

      - name: Push to ECR
        run:
          docker push ${{ secrets.ECR_REPO_URL }}:latest

      - name: Generate task definition
        run: |
          echo '{
            "family": "static-app-task",
            "networkMode": "awsvpc",
            "executionRoleArn": "arn:aws:iam::886557786805:role/ecsTaskExecutionRole",
            "containerDefinitions": [
              {
                "name": "static-app-container",
                "image": "${{ secrets.ECR_REPO_URL }}:latest",
                "portMappings": [
                  { "containerPort": 80, "hostPort": 80 }
                ],
                "essential": true
              }
            ],
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512"
          }' > taskdef.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: taskdef
          path: taskdef.json

      - name: list artifacts
        run: ls -l